### PR TITLE
Nazakat left docuport menu

### PR DESCRIPTION
**Pull request by JuliGV**
perfect👍

### CODE REVIEW

**Comment by Nazakat2335** [comment]
@Shefeg-7  could u pls check my code

**Comment by Nazakat2335** [comment]
@Safailaliyev could u pls see my code?

**Comment by Nazakat2335** [comment]
@frankSerrano07 could u pls see my code?

**Comment by Safailaliyev** [comment]
> @Safailaliyev could u pls see my code?

Nice!

**Pull request merged**
